### ISSUE TITLE
doubleslash in serviceurl

### ISSUE THREAD

**Issue by klausdk** [simplesamlphp/simplesamlphp-module-casserver#18]
We just upgraded to simplesaml v1.17.1 but the problem turns up in the cas module.

Before this url would work : 

`host.xx/saml/module.php/casserver/cas.php//login`   (doubleslashes)

This gives the following error :

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
1 /var/www/simplesamlphp/www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Not a valid function for cas.php.
Backtrace:
2 /var/www/simplesamlphp/modules/casserver/www/cas.php:44 (require)
1 /var/www/simplesamlphp/lib/SimpleSAML/Module.php:236 (SimpleSAML\Module::process)
0 /var/www/simplesamlphp/www/module.php:9 (N/A)
Error report with id 665526a0 generated.
```

It seems that simplesaml has changed the way $_SERVER['PATH_INFO'] is set. It doesn't strip doubleslashes. Normally apache would strip doubleslashes.

As a workaround we added this to cas.php : 
```
$function = substr($_SERVER['PATH_INFO'], 1);
+// remove slashes
+$function = preg_replace('#/#','',$function);
```

At this time we are not able to ask the serviceprovider to correct his code to use only one slash. And we might have others with the same issue.

/Klaus

**Comment by tvdijen** [comment]
Yes, we've moved to `symfony/httpfoundation` for URL-handling.
I'm not sure if this is something we would want to fix on our end though, as to me it feel like an edge case due to misconfiguration on the SP-side.

**Comment by klausdk** [comment]
I agree,

So far we only have one SP with this issue and they are willing to fix, so it might not be a problem afterall.
