### ISSUE TITLE
Proposal for per service configuration

### ISSUE THREAD

**Issue by pradtke** [simplesamlphp/simplesamlphp-module-casserver#19]
We have use cases where we want to control `cas:user`, attribute release and other parts of the CAS configuration based on the service making the login request.

I propose the following changes:
In `module_casserver.php` allow `legal_service_urls` to define an array of configuration options
```php
    'legal_service_urls' => [
        'http://host1.domain:1234/path1',
        'https://host2.domain:5678/path2/path3' =>
        [
              // These will override the values defined in the rest of module_casserver.php
               'attrname' => 'customAttribute',
               'attributes_to_transfer' => ['eduPersonPrincipalName']
        ]
    ],
```
Define a class `CasServiceConfiguration` that would hold CAS configuration options to make it easier to pass around the config for a service

Define a class `ServiceValidator` that would likely replace the existing `urlUtils`.  In the new class the `checkServiceURL` would change slightly including, returning a `CasServiceConfiguration` or `null` for a valid service, rather than true/false.  This returned config would then drive the behavior of `login.php`, `serviceValidate.php`, etc.

**Comment by tvdijen** [comment]
No need for a configuration class.. You can just reuse `\SimpleSAML\Configuration` for that.. Other than that I can't really judge your proposal since I have no clue what this module does :'D

**Comment by pradtke** [comment]
Merged as part of  #PR-21
