### ISSUE TITLE
Implement low-level CAS-library

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp-module-casserver#38]
I've written a low-level CAS-[library ](https://github.com/simplesamlphp/cas)and now it's time to use it for this module!

**Comment by pradtke** [comment]
@tvdijen Awesome!  I'm going to be in and out of the office for next month, but can help you with testing or other stuff when I'm back.

**Comment by tvdijen** [comment]
@pradtke Are you still using this module? If not, I think it's time to archive it.

**Comment by pradtke** [comment]
We do use it.  Reading through this thread I sure was optimistic about my time availability back in 2022 :)
I know you have a lot of modules to wrangle, and if you want us to take over as maintainers let me know.
