### ISSUE TITLE
Redis TicketStore support?

### ISSUE THREAD

**Issue by mattrice** [simplesamlphp/simplesamlphp-module-casserver#8]
I am trying to move away from Memcache (and Memcached) in favor of Redis; I would really like to see Redis supported as a ticket store in this project as well.

In theory, Redis would be much the same as [the Memcache ticket store](https://github.com/simplesamlphp/simplesamlphp-module-casserver/blob/master/lib/Cas/Ticket/MemCacheTicketStore.php), particularly since SimpleSAMLphp [supports Redis as a data store since v1.15.0](https://simplesamlphp.org/docs/1.15/simplesamlphp-changelog#section_1_1) ([pull request to add Redis support](https://github.com/simplesamlphp/simplesamlphp/issues/574), [commit that adds Redis support](https://github.com/tvdijen/simplesamlphp/commit/c8a45c470cdf2e0d8248df944d950c1c6d21160f))

**Comment by tvdijen** [comment]
This has been implemented in 476f9eb11c161442cc81cba739c934d0e712e9b9
